### ISSUE TITLE
how to transform edge cut to vertex cut

### ISSUE THREAD

**Issue by bookug** [zongshenmu/GraphPartitioners#1]
in the ending of split function in ne.cpp,  the edge cut is transformed to vertex cut.
Is the transformed partition still good?
Is the transformation idea from any paper?

**Comment by bookug** [comment]
说反了，NE原本就是切点的图划分，程序最后应该是把它转换为切边的图划分了

**Comment by YijianLiu** [comment]
问题解决了吗，所以还是按边切分？

> 说反了，NE原本就是切点的图划分，程序最后应该是把它转换为切边的图划分了

**Comment by bookug** [comment]
不算是问题。ne本来是切点的，程序中把它改成切边了。我就想知道这种转换方法是否有什么出处，转换后作为切边算法，是否还能保证效果？

**Comment by zongshenmu** [comment]
这个没有问题吧，参考的NE源代码(https://github.com/ansrlab/edgepart)，NE作为edge partitioning就是一种vertex-cut的算法，实现的就是边平衡导致结点的重复

**Comment by bookug** [comment]
NE源代码实现的确实是vertex-cut，但您的代码似乎做了一些修改，在最后把它转换成edge-cut了？想知道这种转换是否是某些论文提出的

**Comment by zongshenmu** [comment]
我看了一下，ne是边分割，我们只是根据度信息选择将重复节点放在某一个partition中，官方代码也有对节点的分配这个和partition的目标无关，只是为了方便你后续对节点的操作

**Comment by bookug** [comment]
ne很明确 是以边为中心的划分，也就是点会被切开来在多台机器存在，但每条边只存在于一台机器上。在您的代码最后，根据度信息把重复节点只放在一个partition，那么这就已经不再是以边为中心的划分了，而是以点为中心的划分（切开的是边）。

**Comment by bookug** [comment]
官方代码里我应该是没有看到类似的处理。如果您的代码最后这段处理来源于ne官方或是其它仓库/论文，请帮忙明确指出下
